# Generated by Django 5.2.4 on 2026-07-11 08:52

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text="Social share preview image. Falls back to the page's own hero/cover image at serialization time, then SEOSettings.default_og_image.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='blogposttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='content.blogtag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='client logo'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text="Social share preview image. Falls back to the page's own hero/cover image at serialization time, then SEOSettings.default_og_image.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='thumbnail'),
        ),
        migrations.AddField(
            model_name='casestudygalleryimage',
            name='case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.casestudy', verbose_name='case study'),
        ),
        migrations.AddField(
            model_name='casestudygalleryimage',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.mediaasset', verbose_name='media'),
        ),
        migrations.AddField(
            model_name='casestudytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.casestudy'),
        ),
        migrations.AddField(
            model_name='faqtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.faq'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='content.industry', verbose_name='client industry'),
        ),
        migrations.AddField(
            model_name='industrytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.industry'),
        ),
        migrations.AddField(
            model_name='processsteptranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.processstep'),
        ),
        migrations.AddField(
            model_name='service',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='hero image'),
        ),
        migrations.AddField(
            model_name='service',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='services', to='content.industry', verbose_name='industries'),
        ),
        migrations.AddField(
            model_name='service',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text="Social share preview image. Falls back to the page's own hero/cover image at serialization time, then SEOSettings.default_og_image.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='Open Graph image'),
        ),
        migrations.AddField(
            model_name='service',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by'),
        ),
        migrations.AddField(
            model_name='service',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AddField(
            model_name='faq',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.service', verbose_name='related service'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='case_studies', to='content.service', verbose_name='related services'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='content.servicecategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='servicetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.service'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to=settings.AUTH_USER_MODEL, verbose_name='linked user account'),
        ),
        migrations.AddIndex(
            model_name='technology',
            index=models.Index(fields=['category', 'is_active'], name='idx_tech_category_active'),
        ),
        migrations.AddField(
            model_name='service',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='services', to='content.technology', verbose_name='technologies'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='case_studies', to='content.technology', verbose_name='technologies'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='client avatar'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_case_study',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='content.casestudy', verbose_name='related case study'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='content.service', verbose_name='related service'),
        ),
        migrations.AddConstraint(
            model_name='blogposttranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='content_blogpost_translation_uniq_lang'),
        ),
        migrations.AlterUniqueTogether(
            name='blogposttranslation',
            unique_together={('language_code', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='casestudytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='content_casestudy_translation_uniq_lang'),
        ),
        migrations.AlterUniqueTogether(
            name='casestudytranslation',
            unique_together={('language_code', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='faqtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='content_faq_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='industrytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='content_industry_translation_uniq_lang'),
        ),
        migrations.AlterUniqueTogether(
            name='industrytranslation',
            unique_together={('language_code', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='processsteptranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='content_processstep_translation_uniq_lang'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['service', 'is_active'], name='idx_faq_service_active'),
        ),
        migrations.AddConstraint(
            model_name='servicetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='content_service_translation_uniq_lang'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetranslation',
            unique_together={('language_code', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='testimonial',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='chk_testimonial_rating_range'),
        ),
    ]
