# Generated by Django 5.2.4 on 2026-07-20 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_service_advanced_enterprise_features'),
        ('core', '0003_alter_mediaasset_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICapability',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('nlp', 'NLP'), ('computer_vision', 'Computer Vision'), ('predictive_analytics', 'Predictive Analytics'), ('generative_ai', 'Generative AI'), ('automation', 'Automation'), ('rag_agents', 'RAG & Agents'), ('mlops', 'MLOps')], db_index=True, max_length=30, verbose_name='category')),
                ('maturity_level', models.CharField(choices=[('research', 'Research'), ('production', 'Production'), ('experimental', 'Experimental')], default='production', max_length=20, verbose_name='maturity level')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji.', max_length=100, verbose_name='icon')),
                ('demo_url', models.URLField(blank=True, verbose_name='demo URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'AI capability',
                'verbose_name_plural': 'AI capabilities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('role_title', models.CharField(blank=True, max_length=200, verbose_name='role title')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'blog author',
                'verbose_name_plural': 'blog authors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BlogHeroImage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('caption', models.CharField(blank=True, help_text='Optional caption or overlay text.', max_length=255, verbose_name='caption')),
                ('is_cover', models.BooleanField(default=False, help_text='If set, this image is the primary cover for the post.', verbose_name='cover image')),
            ],
            options={
                'verbose_name': 'blog hero image',
                'verbose_name_plural': 'blog hero images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('issuer', models.CharField(max_length=200, verbose_name='issuer')),
                ('credential_url', models.URLField(blank=True, verbose_name='credential URL')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='credential ID')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('website_url', models.URLField(blank=True, verbose_name='website URL')),
                ('partner_type', models.CharField(choices=[('technology', 'Technology'), ('implementation', 'Implementation'), ('cloud', 'Cloud'), ('integration', 'Integration'), ('reseller', 'Reseller')], db_index=True, max_length=20, verbose_name='partner type')),
                ('tier', models.CharField(blank=True, choices=[('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=20, verbose_name='tier')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioGalleryImage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='caption')),
            ],
            options={
                'verbose_name': 'portfolio gallery image',
                'verbose_name_plural': 'portfolio gallery images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=270, unique=True, verbose_name='slug')),
                ('short_description', models.TextField(blank=True, verbose_name='short description')),
                ('project_url', models.URLField(blank=True, verbose_name='project URL')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='client name')),
                ('completion_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='completion year')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='featured')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='published')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'portfolio project',
                'verbose_name_plural': 'portfolio projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechExpertiseArea',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Icon class or emoji.', max_length=100, verbose_name='icon')),
                ('category', models.CharField(choices=[('architecture', 'Architecture'), ('cloud', 'Cloud'), ('data_engineering', 'Data Engineering'), ('ai', 'AI'), ('security', 'Security'), ('mobile', 'Mobile'), ('devops', 'DevOps'), ('qa', 'QA')], db_index=True, max_length=30, verbose_name='category')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='display order')),
            ],
            options={
                'verbose_name': 'tech expertise area',
                'verbose_name_plural': 'tech expertise areas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='serviceclientlogo',
            new_name='idx_svccllogo_svc_order',
            old_name='idx_svcclientlogo_service_order',
        ),
        migrations.RenameIndex(
            model_name='servicecomparisonrow',
            new_name='idx_svccompare_svc_order',
            old_name='idx_svccomparison_service_order',
        ),
        migrations.RenameIndex(
            model_name='servicedeliverable',
            new_name='idx_svcdeliv_svc_order',
            old_name='idx_svcdeliverable_service_order',
        ),
        migrations.RenameIndex(
            model_name='servicetestimonial',
            new_name='idx_svctest_svc_order',
            old_name='idx_svctestimonial_service_order',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Icon identifier for the frontend, e.g. 'lucide:book-open'.", max_length=100, verbose_name='icon'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('tutorial', 'Tutorial'), ('case_study', 'Case Study Summary'), ('whitepaper', 'Whitepaper'), ('news', 'News'), ('video_post', 'Video Post')], db_index=True, default='article', max_length=20, verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_url',
            field=models.URLField(blank=True, help_text='For Medium/LinkedIn cross-posts — the original article URL.', verbose_name='external URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this content is gated for lead generation.', verbose_name='premium content'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_case_studies',
            field=models.ManyToManyField(blank=True, related_name='related_blog_posts', to='content.casestudy', verbose_name='related case studies'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='related_blog_posts', to='content.service', verbose_name='related services'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_image',
            field=models.ForeignKey(blank=True, help_text='Small image used in cards, grids, and listing pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='thumbnail image'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo embed URL for video posts.', verbose_name='video embed URL'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='ai_models_used',
            field=models.JSONField(blank=True, default=list, help_text='List of AI/ML models or techniques used, e.g. ["GPT-4", "Computer Vision", "RAG", "Fine-tuning"].', verbose_name='AI models used'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='client_website',
            field=models.URLField(blank=True, help_text="Link to the client's website.", verbose_name='client website'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='is_ai_project',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag for AI/ML specific projects.', verbose_name='AI/ML project'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='key_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Structured business impact data, e.g. {"roi_increase": 340, "cost_reduction": "45%", "performance_gain": "10x"}.', verbose_name='key metrics'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_duration_display',
            field=models.CharField(blank=True, help_text="Human-readable duration, e.g. '6 months', '12 weeks'.", max_length=100, verbose_name='project duration'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_type',
            field=models.CharField(blank=True, choices=[('web_app', 'Web Application'), ('mobile', 'Mobile App'), ('ai_ml', 'AI / Machine Learning'), ('enterprise_integration', 'Enterprise Integration'), ('data_engineering', 'Data Engineering'), ('consulting', 'Consulting')], db_index=True, max_length=30, verbose_name='project type'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='project_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the project was delivered.', null=True, verbose_name='project year'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='team_size',
            field=models.PositiveIntegerField(blank=True, help_text='Number of people who delivered this project.', null=True, verbose_name='team size'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='testimonial',
            field=models.ForeignKey(blank=True, help_text='Direct link to the client quote for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_case_studies', to='content.testimonial', verbose_name='client testimonial'),
        ),
        migrations.AddField(
            model_name='casestudygalleryimage',
            name='image_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('design', 'Design Mockup'), ('demo', 'Demo'), ('architecture', 'Architecture Diagram')], db_index=True, default='screenshot', max_length=20, verbose_name='image type'),
        ),
        migrations.AddField(
            model_name='casestudygalleryimage',
            name='is_before_after',
            field=models.BooleanField(default=False, help_text='If True, this image is part of a before/after comparison slider.', verbose_name='before/after image'),
        ),
        migrations.AddField(
            model_name='industry',
            name='compliance_standards',
            field=models.JSONField(blank=True, default=list, help_text='List of compliance frameworks relevant to this industry, e.g. ["HIPAA", "SOC2", "PCI-DSS"].', verbose_name='compliance standards'),
        ),
        migrations.AddField(
            model_name='industry',
            name='icon_image',
            field=models.ForeignKey(blank=True, help_text='Visual icon asset for this industry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='icon image'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='List of outputs from this step, e.g. ["Requirements document", "Wireframes", "Technical spec"].', verbose_name='deliverables'),
        ),
        migrations.AddField(
            model_name='processstep',
            name='estimated_duration',
            field=models.CharField(blank=True, help_text="e.g. '2-3 weeks', '1 sprint'.", max_length=100, verbose_name='estimated duration'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, help_text='SEO-rich description for category landing pages.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='icon_image',
            field=models.ForeignKey(blank=True, help_text='Visual icon asset for this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='icon image'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_visible_on_nav',
            field=models.BooleanField(db_index=True, default=True, help_text='Control whether this category appears in the main navigation menu.', verbose_name='visible in navigation'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='certifications',
            field=models.JSONField(blank=True, default=list, help_text='List of certifications, e.g. ["AWS Solutions Architect", "Google Cloud Professional"]', verbose_name='certifications'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text='List of education entries, e.g. [{"degree": "MSc", "institution": "MIT", "year": 2015}].', verbose_name='education'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_available_for_consulting',
            field=models.BooleanField(db_index=True, default=False, verbose_name='available for consulting'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of spoken languages, e.g. ["English", "Spanish"]', verbose_name='languages'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='projects_showcase',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='content.casestudy', verbose_name='projects showcase'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='specializations',
            field=models.JSONField(blank=True, default=list, help_text='List of specialization areas, e.g. ["NLP", "MLOps"]', verbose_name='specializations'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='years of experience'),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description for technology detail pages or tooltips.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='technology',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Official technology logo asset.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='technology',
            name='proficiency_level',
            field=models.CharField(choices=[('expert', 'Expert'), ('advanced', 'Advanced'), ('intermediate', 'Intermediate')], db_index=True, default='advanced', help_text="AUTOMEX's expertise depth in this technology.", max_length=20, verbose_name='proficiency level'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='client_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='content.industry', verbose_name='client industry'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_video_testimonial',
            field=models.BooleanField(db_index=True, default=False, verbose_name='video testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='project_impact',
            field=models.JSONField(blank=True, default=dict, help_text='Key impact metrics, e.g. {"revenue_increase": "40%", "cost_savings": "$2M"}', verbose_name='project impact'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='video thumbnail'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='video URL'),
        ),
        migrations.AlterField(
            model_name='service',
            name='enterprise_features',
            field=models.JSONField(blank=True, default=list, help_text='List of enterprise-tier capabilities, e.g. ["Dedicated team", "SLA guarantee", "24/7 support", "Custom integrations"].', verbose_name='enterprise features'),
        ),
        migrations.AlterField(
            model_name='service',
            name='key_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Structured metrics for display, e.g. {"projects_delivered": 150, "client_satisfaction": 98, "years_experience": 12}.', verbose_name='key metrics'),
        ),
        migrations.AlterField(
            model_name='service',
            name='related_services',
            field=models.ManyToManyField(blank=True, help_text="Cross-linked services shown as 'You might also need'.", to='content.service', verbose_name='related services'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tech_stack_grouped',
            field=models.JSONField(blank=True, default=dict, help_text='Structured technology groups for display, e.g. {"Frontend": ["React", "Next.js"], "Backend": ["Django", "Node.js"], "Cloud": ["AWS", "GCP"]}.', verbose_name='grouped tech stack'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceclientlogo',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecomparisonrow',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicedeliverable',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicedocument',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceheroimage',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='serviceprocessstep',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicesla',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicetestimonial',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['project_type', 'is_ai_project'], name='idx_casestudy_type_ai'),
        ),
        migrations.AddField(
            model_name='aicapability',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='aicapability',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='ai_capabilities', to='content.service', verbose_name='related services'),
        ),
        migrations.AddField(
            model_name='aicapability',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='ai_capabilities', to='content.technology', verbose_name='technologies'),
        ),
        migrations.AddField(
            model_name='blogauthor',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='content.blogauthor', verbose_name='author'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['content_type', 'is_premium'], name='idx_blogpost_type_premium'),
        ),
        migrations.AddField(
            model_name='blogheroimage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_images', to='content.blogpost', verbose_name='blog post'),
        ),
        migrations.AddField(
            model_name='blogheroimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='certification',
            name='badge_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='badge image'),
        ),
        migrations.AddField(
            model_name='certification',
            name='related_services',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='content.service', verbose_name='related services'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='portfoliogalleryimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='cover image'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='content.industry', verbose_name='industry'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='portfolio_projects', to='content.service', verbose_name='services'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='portfolio_projects', to='content.technology', verbose_name='technologies'),
        ),
        migrations.AddField(
            model_name='portfoliogalleryimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='content.portfolioproject', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='techexpertisearea',
            name='case_studies',
            field=models.ManyToManyField(blank=True, related_name='expertise_areas', to='content.casestudy', verbose_name='case studies'),
        ),
        migrations.AddField(
            model_name='techexpertisearea',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='expertise_areas', to='content.technology', verbose_name='technologies'),
        ),
        migrations.AddIndex(
            model_name='blogheroimage',
            index=models.Index(fields=['blog_post', 'order'], name='idx_bloghero_post_order'),
        ),
    ]
