# Generated by Django 5.2.4 on 2026-07-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_aicapability_blogauthor_blogheroimage_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
    ]
