# Generated by Django 5.2.4 on 2026-07-22 16:49

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_blogcategory_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicapability',
            options={'ordering': ['order'], 'verbose_name': 'AI capability', 'verbose_name_plural': 'AI capabilities'},
        ),
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'ordering': ['slug'], 'verbose_name': 'blog author', 'verbose_name_plural': 'blog authors'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['order'], 'verbose_name': 'blog category', 'verbose_name_plural': 'blog categories'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ['slug'], 'verbose_name': 'blog tag', 'verbose_name_plural': 'blog tags'},
        ),
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order'], 'verbose_name': 'certification', 'verbose_name_plural': 'certifications'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order'], 'verbose_name': 'partner', 'verbose_name_plural': 'partners'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order'], 'verbose_name': 'service category', 'verbose_name_plural': 'service categories'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order'], 'verbose_name': 'team member', 'verbose_name_plural': 'team members'},
        ),
        migrations.AlterModelOptions(
            name='techexpertisearea',
            options={'ordering': ['order'], 'verbose_name': 'tech expertise area', 'verbose_name_plural': 'tech expertise areas'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category', 'order'], 'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
        migrations.RemoveField(
            model_name='aicapability',
            name='description',
        ),
        migrations.RemoveField(
            model_name='aicapability',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='role_title',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogheroimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='blogtag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='casestudygalleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfoliogalleryimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='portfolioproject',
            name='title',
        ),
        migrations.RemoveField(
            model_name='serviceaddon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serviceaddon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serviceclientlogo',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='servicecomparisonrow',
            name='feature_name',
        ),
        migrations.RemoveField(
            model_name='servicedeliverable',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicedeliverable',
            name='title',
        ),
        migrations.RemoveField(
            model_name='servicedocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicedocument',
            name='title',
        ),
        migrations.RemoveField(
            model_name='serviceheroimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='servicesla',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicesla',
            name='guarantee_name',
        ),
        migrations.RemoveField(
            model_name='servicesla',
            name='value',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='role_title',
        ),
        migrations.RemoveField(
            model_name='techexpertisearea',
            name='description',
        ),
        migrations.RemoveField(
            model_name='techexpertisearea',
            name='name',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='description',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_company',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='client_role',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='quote',
        ),
        migrations.CreateModel(
            name='AICapabilityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.aicapability')),
            ],
            options={
                'verbose_name': 'AI capability Translation',
                'db_table': 'content_aicapability_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_aicapability_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogAuthorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('role_title', models.CharField(blank=True, max_length=200, verbose_name='role title')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.blogauthor')),
            ],
            options={
                'verbose_name': 'blog author Translation',
                'db_table': 'content_blogauthor_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_blogauthor_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.blogcategory')),
            ],
            options={
                'verbose_name': 'blog category Translation',
                'db_table': 'content_blogcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_blogcategory_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogHeroImageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('caption', models.CharField(blank=True, help_text='Optional caption or overlay text.', max_length=255, verbose_name='caption')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.blogheroimage')),
            ],
            options={
                'verbose_name': 'blog hero image Translation',
                'db_table': 'content_blogheroimage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_blogheroimage_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BlogTagTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.blogtag')),
            ],
            options={
                'verbose_name': 'blog tag Translation',
                'db_table': 'content_blogtag_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_blogtag_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CaseStudyGalleryImageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='caption')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.casestudygalleryimage')),
            ],
            options={
                'verbose_name': 'case study gallery image Translation',
                'db_table': 'content_casestudygalleryimage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_casestudygalleryimage_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CertificationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('issuer', models.CharField(max_length=200, verbose_name='issuer')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.certification')),
            ],
            options={
                'verbose_name': 'certification Translation',
                'db_table': 'content_certification_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_certification_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.partner')),
            ],
            options={
                'verbose_name': 'partner Translation',
                'db_table': 'content_partner_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_partner_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioGalleryImageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='caption')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.portfoliogalleryimage')),
            ],
            options={
                'verbose_name': 'portfolio gallery image Translation',
                'db_table': 'content_portfoliogalleryimage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_portfoliogalleryimage_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('short_description', models.TextField(blank=True, verbose_name='short description')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='client name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.portfolioproject')),
            ],
            options={
                'verbose_name': 'portfolio project Translation',
                'db_table': 'content_portfolioproject_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_portfolioproject_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceAddOnTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.serviceaddon')),
            ],
            options={
                'verbose_name': 'service add-on Translation',
                'db_table': 'content_serviceaddon_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_serviceaddon_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='SEO-rich description for category landing pages.', verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.servicecategory')),
            ],
            options={
                'verbose_name': 'service category Translation',
                'db_table': 'content_servicecategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_servicecategory_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceClientLogoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('client_name', models.CharField(blank=True, help_text='Displayed on hover or as alt text for the logo.', max_length=200, verbose_name='client name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.serviceclientlogo')),
            ],
            options={
                'verbose_name': 'service client logo Translation',
                'db_table': 'content_serviceclientlogo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_serviceclientlogo_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceComparisonRowTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('feature_name', models.CharField(help_text='The feature or capability being compared.', max_length=200, verbose_name='feature name')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.servicecomparisonrow')),
            ],
            options={
                'verbose_name': 'service comparison row Translation',
                'db_table': 'content_servicecomparisonrow_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_servicecomparisonrow_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceDeliverableTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.servicedeliverable')),
            ],
            options={
                'verbose_name': 'service deliverable Translation',
                'db_table': 'content_servicedeliverable_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_servicedeliverable_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceDocumentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.servicedocument')),
            ],
            options={
                'verbose_name': 'service document Translation',
                'db_table': 'content_servicedocument_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_servicedocument_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceHeroImageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('caption', models.CharField(blank=True, help_text='Optional caption or overlay text displayed on the hero image.', max_length=255, verbose_name='caption')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.serviceheroimage')),
            ],
            options={
                'verbose_name': 'service hero image Translation',
                'db_table': 'content_serviceheroimage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_serviceheroimage_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceSLATranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('guarantee_name', models.CharField(help_text="e.g. 'Uptime Guarantee', 'Response Time SLA', '24/7 Support'.", max_length=200, verbose_name='guarantee name')),
                ('value', models.CharField(help_text="e.g. '99.9%', '< 4 hours', 'Always available'.", max_length=100, verbose_name='value')),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of this SLA guarantee.', verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.servicesla')),
            ],
            options={
                'verbose_name': 'service SLA Translation',
                'db_table': 'content_servicesla_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_servicesla_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TeamMemberTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('role_title', models.CharField(max_length=200, verbose_name='role title')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.teammember')),
            ],
            options={
                'verbose_name': 'team member Translation',
                'db_table': 'content_teammember_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_teammember_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TechExpertiseAreaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.techexpertisearea')),
            ],
            options={
                'verbose_name': 'tech expertise area Translation',
                'db_table': 'content_techexpertisearea_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_techexpertisearea_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TechnologyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Detailed description for technology detail pages or tooltips.', verbose_name='description')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.technology')),
            ],
            options={
                'verbose_name': 'technology Translation',
                'db_table': 'content_technology_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_technology_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TestimonialTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('client_name', models.CharField(max_length=200, verbose_name='client name')),
                ('client_role', models.CharField(blank=True, max_length=200, verbose_name='client role')),
                ('client_company', models.CharField(blank=True, max_length=200, verbose_name='client company')),
                ('quote', models.TextField(verbose_name='quote')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.testimonial')),
            ],
            options={
                'verbose_name': 'testimonial Translation',
                'db_table': 'content_testimonial_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_testimonial_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
