# Generated by Django 5.2.4 on 2026-07-11 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('old_path', models.CharField(db_index=True, max_length=500, unique=True, verbose_name='old path')),
                ('new_path', models.CharField(max_length=500, verbose_name='new path')),
                ('is_permanent', models.BooleanField(default=True, verbose_name='permanent (301)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('hit_count', models.PositiveIntegerField(default=0, verbose_name='hit count')),
            ],
            options={
                'verbose_name': 'redirect',
                'verbose_name_plural': 'redirects',
                'ordering': ['old_path'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='media_library/%Y/%m/', verbose_name='file')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], db_index=True, max_length=20, verbose_name='file type')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='size (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width (px)')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height (px)')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='caption')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('site_name', models.CharField(default='AUTOMEX', max_length=150, verbose_name='site name')),
                ('default_meta_title_suffix', models.CharField(blank=True, default=' | AUTOMEX', max_length=100, verbose_name='default title suffix')),
                ('default_meta_description', models.CharField(blank=True, max_length=160, verbose_name='default meta description')),
                ('organization_legal_name', models.CharField(default='AUTOMEX', max_length=200, verbose_name='organization legal name')),
                ('organization_url', models.URLField(default='https://automex.tech', max_length=500, verbose_name='organization URL')),
                ('organization_social_profiles', models.JSONField(blank=True, default=list, help_text="List of profile URLs (LinkedIn, X, GitHub, ...) used in JSON-LD 'sameAs'.", verbose_name='social profile URLs')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='public contact email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='public contact phone')),
                ('google_site_verification', models.CharField(blank=True, max_length=255, verbose_name='Google site verification code')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50, verbose_name='Google Tag Manager ID')),
                ('default_og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='default OG image')),
                ('organization_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='organization logo')),
            ],
            options={
                'verbose_name': 'SEO settings',
                'verbose_name_plural': 'SEO settings',
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.UUIDField(verbose_name='object id')),
                ('version', models.PositiveIntegerField(verbose_name='version')),
                ('status_at_snapshot', models.CharField(max_length=20, verbose_name='status at snapshot')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot data')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='change summary')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='content type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'content revision',
                'verbose_name_plural': 'content revisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_revision_object'), models.Index(fields=['content_type', 'object_id', 'version'], name='idx_revision_obj_version')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'version'), name='uq_revision_object_version')],
            },
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['file_type'], name='idx_media_file_type'),
        ),
    ]
