# Generated by Django 5.2.4 on 2026-07-11 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text="Which consumer this key belongs to, e.g. 'automex-frontend-web'.", max_length=200, verbose_name='name')),
                ('key_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True, verbose_name='key hash')),
                ('prefix', models.CharField(db_index=True, editable=False, help_text='First characters of the raw key, shown in the admin for identification. Not a secret.', max_length=12, verbose_name='key prefix')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='idx_apikey_active')],
            },
        ),
    ]
