# Generated by Django 5.2.4 on 2026-07-11 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='preferred language')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='source page')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='subscribed at')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='unsubscribed at')),
            ],
            options={
                'verbose_name': 'newsletter subscriber',
                'verbose_name_plural': 'newsletter subscribers',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='weekday')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='timezone')),
                ('max_bookings', models.PositiveSmallIntegerField(default=1, verbose_name='max bookings per slot')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'availability slot',
                'verbose_name_plural': 'availability slots',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='chk_slot_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('full_name', models.CharField(max_length=200, verbose_name='full name')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='company')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='job title')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('lead_type', models.CharField(choices=[('contact', 'Contact Form'), ('quote', 'Quote Request'), ('consultation', 'Consultation Booking'), ('newsletter', 'Newsletter Signup'), ('ai_assistant', 'AI Assistant'), ('career', 'Careers')], db_index=True, max_length=20, verbose_name='lead type')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam')], db_index=True, default='new', max_length=20, verbose_name='status')),
                ('budget_range', models.CharField(choices=[('under_10k', 'Under $10,000'), ('10k_50k', '$10,000 – $50,000'), ('50k_150k', '$50,000 – $150,000'), ('150k_plus', '$150,000+'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20, verbose_name='budget range')),
                ('timeline', models.CharField(blank=True, choices=[('asap', 'ASAP'), ('within_1_month', 'Within 1 month'), ('within_3_months', 'Within 3 months'), ('within_6_months', 'Within 6 months'), ('flexible', 'Flexible')], max_length=20, verbose_name='project timeline')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='source page URL')),
                ('referrer_url', models.CharField(blank=True, max_length=500, verbose_name='referrer URL')),
                ('utm_source', models.CharField(blank=True, max_length=150, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=150, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=150, verbose_name='UTM campaign')),
                ('utm_term', models.CharField(blank=True, max_length=150, verbose_name='UTM term')),
                ('utm_content', models.CharField(blank=True, max_length=150, verbose_name='UTM content')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='preferred language')),
                ('score', models.PositiveSmallIntegerField(default=0, verbose_name='lead score')),
                ('is_spam', models.BooleanField(db_index=True, default=False, verbose_name='marked as spam')),
                ('lost_reason', models.CharField(blank=True, max_length=255, verbose_name='lost reason')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='converted at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='content.industry', verbose_name='industry')),
                ('service_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='content.service', verbose_name='service of interest')),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('scheduled_date', models.DateField(verbose_name='scheduled date')),
                ('scheduled_time', models.TimeField(verbose_name='scheduled time')),
                ('timezone', models.CharField(default='UTC', max_length=64, verbose_name='timezone')),
                ('meeting_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Call'), ('in_person', 'In Person')], default='video', max_length=20, verbose_name='meeting type')),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('calendar_provider', models.CharField(blank=True, help_text="e.g. 'google_calendar', 'calendly'.", max_length=50, verbose_name='calendar provider')),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, verbose_name='calendar event id')),
                ('calendar_event_link', models.URLField(blank=True, verbose_name='calendar event link')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='crm.availabilityslot', verbose_name='availability slot')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_bookings', to='crm.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'consultation booking',
                'verbose_name_plural': 'consultation bookings',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='CalculatorSubmission',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('complexity_tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced'), ('enterprise', 'Enterprise')], max_length=20, verbose_name='complexity tier')),
                ('selected_features', models.JSONField(blank=True, default=list, verbose_name='selected features')),
                ('estimated_price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated price (min)')),
                ('estimated_price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated price (max)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('selected_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculator_submissions', to='content.service', verbose_name='selected service')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculator_submissions', to='crm.lead', verbose_name='lead')),
            ],
            options={
                'verbose_name': 'calculator submission',
                'verbose_name_plural': 'calculator submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('activity_type', models.CharField(choices=[('status_change', 'Status Change'), ('note', 'Note'), ('email_sent', 'Email Sent'), ('call', 'Call'), ('meeting', 'Meeting'), ('assigned', 'Assigned'), ('other', 'Other')], db_index=True, max_length=20, verbose_name='activity type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead', verbose_name='lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
            ],
            options={
                'verbose_name': 'lead activity',
                'verbose_name_plural': 'lead activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequestDetail',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('project_description', models.TextField(blank=True, verbose_name='project description')),
                ('estimated_budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated budget (min)')),
                ('estimated_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='estimated budget (max)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_detail', to='crm.lead', verbose_name='lead')),
                ('requested_services', models.ManyToManyField(blank=True, related_name='quote_requests', to='content.service', verbose_name='requested services')),
            ],
            options={
                'verbose_name': 'quote request detail',
                'verbose_name_plural': 'quote request details',
            },
        ),
        migrations.CreateModel(
            name='CostCalculatorRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('complexity_tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('advanced', 'Advanced'), ('enterprise', 'Enterprise')], db_index=True, max_length=20, verbose_name='complexity tier')),
                ('base_price_min', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base price (min)')),
                ('base_price_max', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='base price (max)')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('estimated_duration_weeks_min', models.PositiveSmallIntegerField(default=1, verbose_name='estimated duration (min weeks)')),
                ('estimated_duration_weeks_max', models.PositiveSmallIntegerField(default=4, verbose_name='estimated duration (max weeks)')),
                ('factors', models.JSONField(blank=True, default=dict, help_text="Feature-based multipliers, e.g. {'ai_integration': 1.3}.", verbose_name='pricing factors')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_rules', to='content.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'cost calculator rule',
                'verbose_name_plural': 'cost calculator rules',
                'ordering': ['service', 'complexity_tier'],
                'constraints': [models.UniqueConstraint(fields=('service', 'complexity_tier'), name='uq_calc_rule_service_tier'), models.CheckConstraint(condition=models.Q(('base_price_max__gte', models.F('base_price_min'))), name='chk_calc_price_range')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'created_at'], name='idx_lead_status_created'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'status'], name='idx_lead_type_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email'], name='idx_lead_email'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_lead_assigned_status'),
        ),
        migrations.AddIndex(
            model_name='consultationbooking',
            index=models.Index(fields=['scheduled_date', 'status'], name='idx_booking_date_status'),
        ),
        migrations.AddIndex(
            model_name='consultationbooking',
            index=models.Index(fields=['lead'], name='idx_booking_lead'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['lead', '-created_at'], name='idx_leadactivity_lead_created'),
        ),
    ]
