# Generated by Django 5.2.4 on 2026-07-20 13:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_aicapability_blogauthor_blogheroimage_certification_and_more'),
        ('core', '0003_alter_mediaasset_file'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=270, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('guest_email', models.EmailField(blank=True, max_length=254, verbose_name='guest email')),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='guest tracking token')),
                ('ticket_type', models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('technical_support', 'Technical Support'), ('project_request', 'Project Request'), ('bug_report', 'Bug Report'), ('feedback', 'Feedback'), ('partnership', 'Partnership')], db_index=True, max_length=25, verbose_name='ticket type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting on Customer'), ('waiting_admin', 'Waiting on Admin'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10, verbose_name='priority')),
                ('resolution_summary', models.TextField(blank=True, verbose_name='resolution summary')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed at')),
            ],
            options={
                'verbose_name': 'support ticket',
                'verbose_name_plural': 'support tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='author name')),
                ('author_is_staff', models.BooleanField(default=False, verbose_name='staff message')),
                ('body', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='read')),
            ],
            options={
                'verbose_name': 'ticket message',
                'verbose_name_plural': 'ticket messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='calculatorsubmission',
            name='converted_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.lead', verbose_name='converted lead'),
        ),
        migrations.AddField(
            model_name='calculatorsubmission',
            name='converted_to_lead',
            field=models.BooleanField(default=False, verbose_name='converted to lead'),
        ),
        migrations.AddField(
            model_name='calculatorsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculator_submissions', to=settings.AUTH_USER_MODEL, verbose_name='linked user'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='meeting_link',
            field=models.URLField(blank=True, verbose_name='meeting link'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reminder sent at'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='reschedule_count',
            field=models.PositiveIntegerField(default=0, verbose_name='reschedule count'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedule_chain', to='crm.consultationbooking', verbose_name='rescheduled from'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_bookings', to=settings.AUTH_USER_MODEL, verbose_name='linked user'),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='expected close date'),
        ),
        migrations.AddField(
            model_name='lead',
            name='guest_token',
            field=models.CharField(blank=True, db_index=True, help_text='Random token allowing guests to track their request status.', max_length=64, null=True, unique=True, verbose_name='guest tracking token'),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_channel',
            field=models.CharField(blank=True, choices=[('website', 'Website'), ('linkedin', 'LinkedIn'), ('referral', 'Referral'), ('partner', 'Partner'), ('event', 'Event'), ('other', 'Other')], db_index=True, max_length=20, verbose_name='source channel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to=settings.AUTH_USER_MODEL, verbose_name='linked user'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='attachment'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='is_customer_visible',
            field=models.BooleanField(default=False, help_text='If True, this activity/message is visible to the customer in their dashboard.', verbose_name='customer visible'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='quoterequestdetail',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='admin notes'),
        ),
        migrations.AddField(
            model_name='quoterequestdetail',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='quote_details', to='core.mediaasset', verbose_name='attachments'),
        ),
        migrations.AddField(
            model_name='quoterequestdetail',
            name='quoted_currency',
            field=models.CharField(blank=True, default='USD', max_length=3, verbose_name='quoted currency'),
        ),
        migrations.AddField(
            model_name='quoterequestdetail',
            name='quoted_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='quoted price (max)'),
        ),
        migrations.AddField(
            model_name='quoterequestdetail',
            name='quoted_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='quoted price (min)'),
        ),
        migrations.AddField(
            model_name='quoterequestdetail',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='version'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['user', 'status'], name='idx_lead_user_status'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['priority', 'status'], name='idx_lead_priority_status'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='related_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='crm.lead', verbose_name='related lead'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='content.service', verbose_name='related service'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset', verbose_name='attachment'),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='author_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_messages', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='supportticketmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.supportticket', verbose_name='ticket'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'created_at'], name='idx_ticket_status_created'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='idx_ticket_user_status'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_ticket_assigned_status'),
        ),
        migrations.AddIndex(
            model_name='supportticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='idx_ticketmsg_ticket_created'),
        ),
    ]
