# Generated by Django 5.2.4 on 2026-07-11 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='session id')),
                ('channel', models.CharField(choices=[('website_widget', 'Website Widget'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook Messenger')], default='website_widget', max_length=20, verbose_name='channel')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('lead_captured', models.BooleanField(default=False, verbose_name='lead captured')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='page URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='ended at')),
            ],
            options={
                'verbose_name': 'AI conversation',
                'verbose_name_plural': 'AI conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIKnowledgeEntry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'AI knowledge entry',
                'verbose_name_plural': 'AI knowledge entries',
                'ordering': ['category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='tokens used')),
                ('detected_intent', models.CharField(blank=True, max_length=100, verbose_name='detected intent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'AI message',
                'verbose_name_plural': 'AI messages',
                'ordering': ['created_at'],
            },
        ),
    ]
