# Generated by Django 5.2.4 on 2026-07-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        ('content', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='crm.lead', verbose_name='captured lead'),
        ),
        migrations.AddField(
            model_name='aiknowledgeentry',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_knowledge_entries', to='content.service', verbose_name='related service'),
        ),
        migrations.AddField(
            model_name='aimessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.aiconversation', verbose_name='conversation'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['is_active', '-started_at'], name='idx_aiconv_active_started'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_aimsg_conv_created'),
        ),
    ]
