# Generated by Django 5.2.4 on 2026-07-22 16:49

import django.db.models.deletion
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_aiconversation_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiknowledgeentry',
            options={'ordering': ['category'], 'verbose_name': 'AI knowledge entry', 'verbose_name_plural': 'AI knowledge entries'},
        ),
        migrations.RemoveField(
            model_name='aiknowledgeentry',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='aiknowledgeentry',
            name='question',
        ),
        migrations.CreateModel(
            name='AIKnowledgeEntryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question', models.CharField(max_length=500, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='assistant.aiknowledgeentry')),
            ],
            options={
                'verbose_name': 'AI knowledge entry Translation',
                'db_table': 'assistant_aiknowledgeentry_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='assistant_aiknowledgeentry_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
