# Generated by Django 5.2.4 on 2026-07-11 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProviderConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('slack', 'Slack'), ('in_app', 'In-App')], db_index=True, max_length=20, verbose_name='channel')),
                ('provider_name', models.CharField(help_text="e.g. 'sendgrid', 'twilio', 'slack_webhook', 'whatsapp_cloud_api'.", max_length=100, verbose_name='provider name')),
                ('credentials', models.JSONField(blank=True, default=dict, verbose_name='credentials')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='extra config')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_default', models.BooleanField(default=False, verbose_name='default for channel')),
            ],
            options={
                'verbose_name': 'notification provider config',
                'verbose_name_plural': 'notification provider configs',
                'ordering': ['channel', '-is_default'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('channel',), name='uq_one_default_provider_per_channel')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.SlugField(help_text="Unique identifier, e.g. 'lead_created.email.en'.", max_length=150, unique=True, verbose_name='key')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_assigned', 'Lead Assigned'), ('lead_status_changed', 'Lead Status Changed'), ('quote_requested', 'Quote Requested'), ('consultation_booked', 'Consultation Booked'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_cancelled', 'Consultation Cancelled'), ('newsletter_subscribed', 'Newsletter Subscribed'), ('ai_lead_captured', 'AI Assistant Captured Lead'), ('content_submitted_for_review', 'Content Submitted for Review'), ('content_approved', 'Content Approved'), ('content_published', 'Content Published'), ('content_rejected', 'Content Rejected'), ('system_alert', 'System Alert'), ('custom', 'Custom')], db_index=True, max_length=40, verbose_name='event type')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('slack', 'Slack'), ('in_app', 'In-App')], db_index=True, max_length=20, verbose_name='channel')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='language')),
                ('subject', models.CharField(blank=True, help_text='Used for email/push. Supports {placeholders} resolved from the notification context.', max_length=255, verbose_name='subject')),
                ('body', models.TextField(help_text='Supports {placeholders} resolved from the notification context.', verbose_name='body')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'ordering': ['event_type', 'channel', 'language'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_assigned', 'Lead Assigned'), ('lead_status_changed', 'Lead Status Changed'), ('quote_requested', 'Quote Requested'), ('consultation_booked', 'Consultation Booked'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_cancelled', 'Consultation Cancelled'), ('newsletter_subscribed', 'Newsletter Subscribed'), ('ai_lead_captured', 'AI Assistant Captured Lead'), ('content_submitted_for_review', 'Content Submitted for Review'), ('content_approved', 'Content Approved'), ('content_published', 'Content Published'), ('content_rejected', 'Content Rejected'), ('system_alert', 'System Alert'), ('custom', 'Custom')], db_index=True, max_length=40, verbose_name='event type')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('slack', 'Slack'), ('in_app', 'In-App')], db_index=True, max_length=20, verbose_name='channel')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='recipient email')),
                ('recipient_phone', models.CharField(blank=True, max_length=30, verbose_name='recipient phone')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='rendered body')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='render context')),
                ('object_id', models.UUIDField(blank=True, null=True, verbose_name='related object id')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10, verbose_name='priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='scheduled at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('provider_message_id', models.CharField(blank=True, max_length=255, verbose_name='provider message id')),
                ('failed_reason', models.TextField(blank=True, verbose_name='failed reason')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='retry count')),
                ('max_retries', models.PositiveSmallIntegerField(default=3, verbose_name='max retries')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='related content type')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient (internal user)')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='notifications.notificationtemplate', verbose_name='template')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField(verbose_name='attempt number')),
                ('provider_name', models.CharField(blank=True, max_length=100, verbose_name='provider name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=20, verbose_name='status')),
                ('response_code', models.CharField(blank=True, max_length=20, verbose_name='response code')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='response payload')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration (ms)')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='attempted at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notification', verbose_name='notification')),
            ],
            options={
                'verbose_name': 'notification delivery attempt',
                'verbose_name_plural': 'notification delivery attempts',
                'ordering': ['-attempted_at'],
                'constraints': [models.UniqueConstraint(fields=('notification', 'attempt_number'), name='uq_delivery_attempt_number')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event_type', models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_assigned', 'Lead Assigned'), ('lead_status_changed', 'Lead Status Changed'), ('quote_requested', 'Quote Requested'), ('consultation_booked', 'Consultation Booked'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_cancelled', 'Consultation Cancelled'), ('newsletter_subscribed', 'Newsletter Subscribed'), ('ai_lead_captured', 'AI Assistant Captured Lead'), ('content_submitted_for_review', 'Content Submitted for Review'), ('content_approved', 'Content Approved'), ('content_published', 'Content Published'), ('content_rejected', 'Content Rejected'), ('system_alert', 'System Alert'), ('custom', 'Custom')], max_length=40, verbose_name='event type')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('slack', 'Slack'), ('in_app', 'In-App')], max_length=20, verbose_name='channel')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
                'ordering': ['user', 'event_type', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'channel'), name='uq_notif_pref_user_event_channel')],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationtemplate',
            constraint=models.UniqueConstraint(fields=('event_type', 'channel', 'language'), name='uq_template_event_channel_lang'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'priority', '-created_at'], name='idx_notif_status_prio_created'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_user', 'status'], name='idx_notif_recipient_status'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_notif_related_object'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['event_type', 'channel'], name='idx_notif_event_channel'),
        ),
    ]
