# Generated by Django 5.2.4 on 2026-07-12 19:23

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationproviderconfig',
            name='credentials',
            field=apps.core.fields.EncryptedJSONField(blank=True, default=dict, verbose_name='credentials'),
        ),
    ]
