# Generated by Django 5.2.4 on 2026-07-20 12:52

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_supportticket_supportticketmessage_and_more'),
        ('notifications', '0002_alter_notificationproviderconfig_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Groups notifications sent in the same digest batch.', max_length=100, verbose_name='batch id'),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='read'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='digest_frequency',
            field=models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='instant', max_length=10, verbose_name='digest frequency'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='If set, these preferences apply to this specific lead/client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='crm.lead', verbose_name='lead'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_assigned', 'Lead Assigned'), ('lead_status_changed', 'Lead Status Changed'), ('quote_requested', 'Quote Requested'), ('consultation_booked', 'Consultation Booked'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_cancelled', 'Consultation Cancelled'), ('newsletter_subscribed', 'Newsletter Subscribed'), ('ai_lead_captured', 'AI Assistant Captured Lead'), ('content_submitted_for_review', 'Content Submitted for Review'), ('content_approved', 'Content Approved'), ('content_published', 'Content Published'), ('content_rejected', 'Content Rejected'), ('system_alert', 'System Alert'), ('custom', 'Custom'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_message', 'Ticket Message'), ('ticket_resolved', 'Ticket Resolved'), ('quote_received', 'Quote Received'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('request_status_changed', 'Request Status Changed'), ('request_submitted', 'Request Submitted')], db_index=True, max_length=40, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_assigned', 'Lead Assigned'), ('lead_status_changed', 'Lead Status Changed'), ('quote_requested', 'Quote Requested'), ('consultation_booked', 'Consultation Booked'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_cancelled', 'Consultation Cancelled'), ('newsletter_subscribed', 'Newsletter Subscribed'), ('ai_lead_captured', 'AI Assistant Captured Lead'), ('content_submitted_for_review', 'Content Submitted for Review'), ('content_approved', 'Content Approved'), ('content_published', 'Content Published'), ('content_rejected', 'Content Rejected'), ('system_alert', 'System Alert'), ('custom', 'Custom'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_message', 'Ticket Message'), ('ticket_resolved', 'Ticket Resolved'), ('quote_received', 'Quote Received'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('request_status_changed', 'Request Status Changed'), ('request_submitted', 'Request Submitted')], max_length=40, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='event_type',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_assigned', 'Lead Assigned'), ('lead_status_changed', 'Lead Status Changed'), ('quote_requested', 'Quote Requested'), ('consultation_booked', 'Consultation Booked'), ('consultation_reminder', 'Consultation Reminder'), ('consultation_cancelled', 'Consultation Cancelled'), ('newsletter_subscribed', 'Newsletter Subscribed'), ('ai_lead_captured', 'AI Assistant Captured Lead'), ('content_submitted_for_review', 'Content Submitted for Review'), ('content_approved', 'Content Approved'), ('content_published', 'Content Published'), ('content_rejected', 'Content Rejected'), ('system_alert', 'System Alert'), ('custom', 'Custom'), ('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_message', 'Ticket Message'), ('ticket_resolved', 'Ticket Resolved'), ('quote_received', 'Quote Received'), ('booking_confirmed', 'Booking Confirmed'), ('booking_reminder', 'Booking Reminder'), ('request_status_changed', 'Request Status Changed'), ('request_submitted', 'Request Submitted')], db_index=True, max_length=40, verbose_name='event type'),
        ),
        migrations.CreateModel(
            name='ThirdPartyIntegration',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('provider_type', models.CharField(choices=[('smtp', 'SMTP / Email'), ('sms', 'SMS'), ('ai', 'AI / LLM'), ('cloud_storage', 'Cloud Storage'), ('analytics', 'Analytics'), ('chat', 'Chat / Messaging'), ('crm', 'CRM'), ('payment', 'Payment')], db_index=True, max_length=20, verbose_name='provider type')),
                ('provider_name', models.CharField(help_text="e.g. 'google_smtp', 'hostinger_smtp', 'twilio', 'groq', 'openai'.", max_length=100, verbose_name='provider name')),
                ('credentials', apps.core.fields.EncryptedJSONField(blank=True, default=dict, help_text='Encrypted at rest. SMTP example: {"host": "smtp.gmail.com", "port": 587, "use_tls": true, "username": "user@domain.com", "password": "...", "from_email": "noreply@domain.com"}. Twilio example: {"account_sid": "...", "auth_token": "...", "from_number": "..."}.', verbose_name='credentials')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret configuration: timeouts, rate limits, feature flags.', verbose_name='extra config')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_default_for_type', models.BooleanField(default=False, help_text='If True, this is the default provider for its type (e.g. default SMTP).', verbose_name='default for provider type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='last tested at')),
                ('last_test_result', models.CharField(blank=True, help_text="e.g. 'success', 'failed: connection timeout', 'failed: auth error'.", max_length=255, verbose_name='last test result')),
            ],
            options={
                'verbose_name': 'third-party integration',
                'verbose_name_plural': 'third-party integrations',
                'ordering': ['provider_type', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_for_type', True)), fields=('provider_type',), name='uq_one_default_integration_per_type')],
            },
        ),
        migrations.AddField(
            model_name='notificationproviderconfig',
            name='integration',
            field=models.ForeignKey(blank=True, help_text='Link to the centralized ThirdPartyIntegration registry for credentials.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_configs', to='notifications.thirdpartyintegration', verbose_name='linked integration'),
        ),
    ]
